name: Build LaTeX CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Upload PDF to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4 
        with:
          name: PDF
          path: cv.pdf

      - name: Create Release and Upload PDF
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2 
        with:
          files: cv.pdf 
          tag_name: latest
          name: Latest Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
